program: main.py
name: sweep
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  learning_rate:
    min: 0.001
    max: 0.005
  reconstruction_coefficient:
    values:
      [
        4_000_000.0,
        8_000_000.0,
        16_000_000.0,
        36_000_000.0,
        64_000_000.0,
        128_000_000.0,
        256_000_000.0,
        512_000_000.0,
        1_024_000_000.0,
      ]
  stddev_prior:
    min: 0.001
    max: 0.04
