program: main.py
name: sweep
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  learning_rate:
    min: 0.00001
    max: 0.005
  reconstruction_coefficient:
    min: 4e4
    max: 2e5
  stddev_prior:
    min: 0.005
    max: 0.04
