program: main.py
name: sweep
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  learning_rate:
    min: 0.00001
    max: 0.005
  reconstruction_coefficient:
    min: 40000.0
    max: 200000.0
  stddev_prior:
    min: 0.005
    max: 0.04
